-- V1__baseline.sql
-- Esquema completo inicial del ecosistema TipsterByte FX (H-05 / FASE 19 adelantada).
--
-- [POR QUÉ]: Única fuente de verdad del esquema a partir de ahora. Generado desde las
--            entidades JPA (schema-generation scripts) para garantizar coincidencia
--            exacta con el dominio; validado por la suite completa (Testcontainers).
-- [NOTAS]
--   - ddl-auto pasa a validate: Hibernate ya NO modifica el esquema.
--   - En BD existentes (dev :5434) se usa baseline-on-migrate=true: Flyway marca esta
--     versión como aplicada sin ejecutarla (cero impacto sobre datos).
--   - Los CHECK de enums reflejan los valores vigentes post-refactor Temporadas y #6.

create table cuotas (valor numeric(10,2) not null, id bigint generated by default as identity, partido_id uuid not null, mercado varchar(20) not null check ((mercado in ('UNO_X_DOS','DOBLE_OPORTUNIDAD','OVER_UNDER'))), primary key (id));
create table detalle_fuentes_extraccion (activa boolean not null, fuente_id uuid not null, id uuid not null, temporada_id uuid not null, tipo varchar(20) not null check ((tipo in ('STANDINGS','ODDS_WPLAY','CALENDAR','EQUIPOS'))), url varchar(500) not null, primary key (id), constraint uk_detalle_fuente_temporada_tipo unique (temporada_id, tipo));
create table equipos (id uuid not null, temporada_id uuid not null, nombre varchar(100) not null, logo_url varchar(300), primary key (id));
create table fuentes_extraccion (activa boolean not null, id uuid not null, tipo varchar(20) not null unique check ((tipo in ('STANDINGS','ODDS_WPLAY','CALENDAR','EQUIPOS'))), nombre varchar(100) not null, primary key (id));
create table ligas (id uuid not null, pais_id uuid, estado varchar(20) not null check ((estado in ('BORRADOR','ACTIVA','INACTIVA'))), api_id varchar(50), pais varchar(60) not null, nombre varchar(100) not null, url_soccerway varchar(300), primary key (id));
create table paises (iso_alpha2 varchar(2) not null unique, mapeado boolean not null, id uuid not null, code varchar(20), continente varchar(40) not null, nombre varchar(100) not null, href varchar(200), primary key (id));
create table paises_interes (iso_alpha2 varchar(2) not null unique, max_ligas_por_pais integer, prioridad integer not null, id uuid not null, nombre varchar(100) not null, primary key (id));
create table partidos (jornada integer, resultado_goles_local integer, resultado_goles_visitante integer, fecha_hora timestamp(6) not null, equipo_local_id uuid not null, equipo_visitante_id uuid not null, id uuid not null, temporada_id uuid not null, estado varchar(20) not null check ((estado in ('PROGRAMADO','EN_VIVO','FINALIZADO','SUSPENDIDO'))), equipo_local_nombre varchar(100) not null, equipo_visitante_nombre varchar(100) not null, primary key (id));
create table posiciones_tabla (empatados integer not null, ganados integer not null, goles_contra integer not null, goles_favor integer not null, jugados integer not null, perdidos integer not null, posicion integer not null, puntos integer not null, id bigint generated by default as identity, ultimos_resultados varchar(9), equipo_id uuid not null, temporada_id uuid not null, primary key (id));
create table pronosticos (cuota_valor numeric(10,2) not null, resultado_final_goles_local integer, resultado_final_goles_visitante integer, resultado_esperado varchar(10) not null, id uuid not null, partido_id uuid not null, tipster_id uuid not null, estado varchar(20) not null check ((estado in ('BORRADOR','PUBLICADO','ANULADO'))), mercado varchar(20) not null check ((mercado in ('UNO_X_DOS','DOBLE_OPORTUNIDAD','OVER_UNDER'))), primary key (id));
create table suscripciones (plan_duracion_dias integer not null, plan_precio numeric(10,2) not null, fecha_fin timestamp(6) not null, fecha_inicio timestamp(6) not null, cliente_id uuid not null, id uuid not null, tipster_id uuid not null, estado varchar(20) not null check ((estado in ('ACTIVA','CANCELADA','EXPIRADA'))), plan_nombre varchar(60) not null, primary key (id));
create table tarea_log (duration_ms bigint, timestamp timestamp(6) with time zone not null, id uuid not null, tarea_programada_id uuid, execution_id varchar(36) not null, error_code varchar(255), mensaje varchar(255), status varchar(255) not null, primary key (id));
create table tareas_programadas (activa boolean, id uuid not null, liga_id uuid, created_at varchar(255), cron_expression varchar(255), prioridad varchar(255), tipo_fuente varchar(255) check ((tipo_fuente in ('STANDINGS','ODDS_WPLAY','CALENDAR','EQUIPOS'))), primary key (id));
create table temporadas (anio_fin integer not null, anio_inicio integer not null, semestre integer, id uuid not null, liga_id uuid not null, nombre varchar(100) not null, estado varchar(255) not null check ((estado in ('PLANIFICADA','ACTIVA','FINALIZADA'))), primary key (id), unique (liga_id, nombre));
create table usuarios (activo boolean not null, fecha_creacion timestamp(6) not null, id uuid not null, rol varchar(20) not null check ((rol in ('CLIENTE','TIPSTER','SUPERADMIN'))), nombre varchar(100) not null, password_hash varchar(100) not null, email varchar(150) not null unique, primary key (id));
alter table cuotas add constraint fk_cuotas_partido foreign key (partido_id) references partidos;
alter table detalle_fuentes_extraccion add constraint fk_detalle_fuentes_fuente foreign key (fuente_id) references fuentes_extraccion;
alter table detalle_fuentes_extraccion add constraint fk_detalle_fuentes_temporada foreign key (temporada_id) references temporadas;
alter table equipos add constraint fk_equipos_temporada foreign key (temporada_id) references temporadas;
alter table ligas add constraint fk_ligas_pais foreign key (pais_id) references paises;
alter table partidos add constraint fk_partidos_temporada foreign key (temporada_id) references temporadas;
alter table posiciones_tabla add constraint fk_posiciones_tabla_equipo foreign key (equipo_id) references equipos;
alter table posiciones_tabla add constraint fk_posiciones_tabla_temporada foreign key (temporada_id) references temporadas;
alter table temporadas add constraint fk_temporadas_liga foreign key (liga_id) references ligas;
